//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [42.38884279, -83.33090463]	_	2014-02-16 03:14:30	@TheMattEspinosa: First poop in Cali oh yeah http://t.co/4G6xvUtSY5
        ///[26.2250129, -80.2956435]	_	2014-02-16 03:15:02	@Pachovelez10 sera que el Cali estaba jugando solo? Le recuerdo que venia de recibir 10 goles en 6 partidos y lleva dos sin recibir
        ///[32.59617319, -115.42837369]	_	2014-02-16 03:16:17	No TU in Cali, but TU in Mexico! 
        ///[37.0261157, -76.3764071]	_	2014-02-16 03:16:31	Texas, Vegas, Cali, and Washington this Summer. Then Mexico, Brazil, and London l [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string cali_tweets2014 {
            get {
                return ResourceManager.GetString("cali_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [44.08509718, -93.24939365]	_	2014-02-16 03:11:36	Hanging out with @beeker04 family without her. #truecuz
        ///[33.3522495, -111.4540254]	_	2014-02-16 03:14:24	So grateful that my dad is okay, aside from him having a tube down his nose, goes to show you to be thankful for your family, and love them.
        ///[30.30737463, -97.70697607]	_	2014-02-16 03:14:27	Support team ready to help thanks Holub family for the support team holub! Super http://t.co/LBTQX51YUD
        ///[30.30737463, -97.70697607]	_	2014-02-16 03:14:27	Support team [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string family_tweets2014 {
            get {
                return ResourceManager.GetString("family_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [31.2784485, -90.46151438]	_	2014-02-16 03:14:35	watching a football life 
        ///[41.68770968, -71.16827271]	_	2014-02-16 03:15:18	Is it bad that I already miss football season?
        ///[37.96682961, -84.45854165]	_	2014-02-16 03:15:57	but a few years ago FL had a good football team and now they have a good basketball team that&apos;s not fair
        ///[40.092657, -88.23893792]	_	2014-02-16 03:16:41	It&apos;s really sad when the ILL vs OSU football game has more points than the basketball game. #pathetic
        ///[26.70290653, -80.22700978]	_	2014- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string football_tweets2014 {
            get {
                return ResourceManager.GetString("football_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [30.66978636, -88.14511087]	_	2014-02-16 03:14:35	@Jeffsnation let&apos;s see a one million high school graduation walk, with their families; bring their college acceptance letters
        ///[30.66978636, -88.14511087]	_	2014-02-16 03:14:35	@Jeffsnation let&apos;s see a one million high school graduation walk, with their families; bring their college acceptance letters
        ///[33.84847802, -78.65874211]	_	2014-02-16 03:15:25	I don&apos;t even go to high school anymore and I&apos;m annoyed
        ///[33.38723009, -111.84785602]	_	2014-02-16 03:15:28	It&apos;s [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string high_school_tweets2014 {
            get {
                return ResourceManager.GetString("high_school_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [36.56652086, -96.70504544]	_	2014-02-16 03:11:33	Going to watch a scary movie, drink a pop that I&apos;m not supposed to drink, and turn my phone off... Lovely Saturday for Katzee.
        ///[45.56401799, -94.23024965]	_	2014-02-16 03:14:23	The Lego movie was pretty adorable
        ///[37.76268757, -122.43868215]	_	2014-02-16 03:14:27	Dinner last night included beans. Popcorn at the subsequent movie. Youd be uptight, too, if your home bathrooms were unavailable all day.
        ///[33.96750648, -84.04567326]	_	2014-02-16 03:14:33	Fast and fu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string movie_tweets2014 {
            get {
                return ResourceManager.GetString("movie_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;hood,-0.375
        ///0,-0.5
        ///1,-0.25
        ///101,-0.25
        ///105,-0.25
        ///2 esdras,0.25
        ///2-dimensional,-0.625
        ///300,-0.25
        ///365 days,-0.5
        ///366 days,0.25
        ///3tc,-0.25
        ///400,-0.25
        ///a fortiori,0.25
        ///a good deal,0.25
        ///a great deal,0.25
        ///a lot,0.25
        ///a priori,0.25
        ///a-one,0.625
        ///abandon,-0.375
        ///abandoned person,-0.375
        ///abandoned,-0.375
        ///abase,-0.625
        ///abash,-0.25
        ///abashed,-0.375
        ///abashment,-0.375
        ///abasia trepidans,-0.375
        ///abasia,-0.5
        ///abasic,-0.25
        ///abatable,0.625
        ///abatic,-0.25
        ///abaxially,0.25
        ///abbot,0.5
        ///abdias,-0.25
        ///abdicable,0.375
        ///abdominal breathing,-0.25
        ///aberrant,0.37 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sentiments {
            get {
                return ResourceManager.GetString("sentiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [39.05364937, -94.61706306]	_	2014-02-16 03:11:35	I&apos;m already Spring shopping. I am completely over this ice!
        ///[43.73412537, -79.26058129]	_	2014-02-16 03:14:55	Shopping with my mum&amp;gt;&amp;gt;&amp;gt;
        ///[44.94200452, -123.0359108]	_	2014-02-16 03:16:03	Shopping with miss thing @NenaaLemus
        ///[44.94200452, -123.0359108]	_	2014-02-16 03:16:03	Shopping with miss thing @NenaaLemus
        ///[26.16054656, -97.88843639]	_	2014-02-16 03:16:36	I love shopping but I hate it ..
        ///[39.92389848, -75.30000278]	_	2014-02-16 03:16:52	shopping is  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string shopping_tweets2014 {
            get {
                return ResourceManager.GetString("shopping_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [35.84553051, -84.51712503]	_	2014-02-16 03:11:36	@10weather nice burst of snow in Kingston. http://t.co/tp7iLz5ID3
        ///[36.04406781, -83.3726885]	_	2014-02-16 03:14:27	&quot;The snow is soft like marbles&quot; #SochiProblems
        ///[40.6636977, -74.2166277]	_	2014-02-16 03:14:31	Wow 49 states had snow this week that must be a record
        ///[39.77082218, -75.88280386]	_	2014-02-16 03:14:40	&quot;The snow is soft as marbles&quot; The Announcer&quot;Wow that really paints a picture for me&quot; My Father 
        ///[36.05438302, -94.15702998]	_	2014-02-16 03:14:43	S [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string snow_tweets2014 {
            get {
                return ResourceManager.GetString("snow_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] states {
            get {
                object obj = ResourceManager.GetObject("states", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [33.19788789, -96.6159409]	_	2014-02-16 03:14:57	Being very spoiled tonight. #dinner #culinaryadventure #valentinegetaway #mckinney #texas http://t.co/cUF6pkkyPq
        ///[30.59253179, -96.32883813]	_	2014-02-16 03:15:02	#Texas
        ///[29.70992273, -95.40337593]	_	2014-02-16 03:15:03	I&apos;m at hilton plaza houston texas (Houston, TX) http://t.co/mDaTb8VB9f
        ///[32.35060996, -99.71554359]	_	2014-02-16 03:15:10	Texas!  #Texas http://t.co/y9xcQT1NNy
        ///[37.0261157, -76.3764071]	_	2014-02-16 03:16:31	Texas, Vegas, Cali, and Washington t [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string texas_tweets2014 {
            get {
                return ResourceManager.GetString("texas_tweets2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [38.29835689, -122.28522354]	_	2014-02-16 03:11:33	Great wine with a great name to kick off the Napa Weekend! missay222 @ Carpe Diem Wine Bar http://t.co/Cwh9q02nJH
        ///[42.30439381, -71.06777494]	_	2014-02-16 03:11:33	Thinking bout that ink this weekend.
        ///[43.00234789, -88.22758371]	_	2014-02-16 03:11:39	I&apos;m going to be at all star weekend real soon!!
        ///[31.91069296, -92.64220147]	_	2014-02-16 03:11:40	THE MOVEMENT FOR NEXT WEEKEND ! http://t.co/uwMbxdiZb7
        ///[35.58836606, -120.6980953]	_	2014-02-16 03:11:40	Birthda [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string weekend_tweets2014 {
            get {
                return ResourceManager.GetString("weekend_tweets2014", resourceCulture);
            }
        }
    }
}
